### ISSUE TITLE
Point -> Añadir tercera coordenada

### ISSUE THREAD

**Issue by dpb-upm** [dpb-upm/IWVG.SwC.DanielPerez#1]
Se añadirá una tercera coordenada a la clase.

Mas info [aquí](https://github.com/dpb-upm/IWVG.SwC.DanielPerez/wiki#clase-point)

**Comment by AngelicaGuaman** [comment]
Hola Daniel, 
¿Tendría que modificar los método **module**, **phase**, **translateOrigin**?

**Comment by dpb-upm** [comment]
Solo el método translateOrigin,  que mueve el punto por completo.

**Comment by AngelicaGuaman** [comment]
Habría que cambiar el nombre de module y phase para que se corresponda que solo se hace para las coordenadas x e y, no?

**Comment by dpb-upm** [comment]
Si, cambiale el nombre, así queda mas claro.
