### ISSUE TITLE
Eliminar comentarios de código

### ISSUE THREAD

**Issue by dpb-upm** [dpb-upm/IWVG.SwC.DanielPerez#7]
En el proyecto hay líneas de código comentadas. Hay que borrarlas para que en sonar pase el test.

**Comment by robertome** [comment]
@dpb-upm no veo nota en el tablon kanban asociada a este ticket.
Ya esta resuelta

**Comment by dpb-upm** [comment]
Hola, he observado que no has subido la rama issue#4 al remoto, ¿Podrías subir la rama para que conste en github?

Gracias :)

**Comment by robertome** [comment]
Subida rama local issue#7 a repositorio remoto para que conste
