### ISSUE TITLE
Test que cubrir

### ISSUE THREAD

**Issue by dpb-upm** [dpb-upm/IWVG.SwC.DanielPerez#9]
Se necesita crear test para todos estos métodos ya que no están cubiertos.

* Clase Point

- [x] Al método toString

* Clase User

- [x] Al método initials, 
- [x] Al método getNumber
- [x] Al método getName
- [x] Al método getFamilyName

* Clase Fraction

- [x] Al constructor sin parámetros. Se require un test para el constructor de la fracción que se crea con 1/1, ya que no está cubierto.

**Comment by dpb-upm** [comment]
Hay métodos en el proyecto que hay que cubrir con test para saber que funcionan. ¿Alguien se presta voluntario?. Se puede dividir en partes :)

**Comment by dpb-upm** [comment]
Se cierra el issue ya que el objetivo de la práctica no es mejorar la calidad del código basándonos en sonar. Al menos no se indicar en la memoria de la práctica.

**Comment by dpb-upm** [comment]
Reabro el issue, para que el cliente tenga un código con mejor calidad.

@robertome te asigno a ti la tarea, ya que estás lire y no debería llevarte mucho tiempo en implementar estos test. Gracias :)

**Comment by robertome** [comment]
Subida rama local issue#9 a repositorio remoto para que conste
